### ISSUE TITLE
User Credentials not Validated during SDNExpress Deployment

### ISSUE THREAD

**Issue by JMesser81** [Microsoft/SDN#13] opened 2016-01-30 00:59 UTC
I changed my domain account's password after it had expired and tried to re-run the SDNExpress scripts. The scripts failed to complete most notably because the Network Controller could not be accessed. I discovered later that I forgot to update my password in the configuration file (FabricConfig.psd1).

We should add a mechanism to either request new user credentials each time the script is run or at least validate that the current domain account is valid and usable. Right now, there is no intelligible error produced when the domain account referenced is incorrect.

**Comment by manishmsft** [comment] 2016-10-14 07:35
thanks for reporting this Jason. I will get this updated.

**Comment by manishmsft** [comment] 2016-12-14 09:11
Hello Jason,

with the current design, VMMExpress does not validate the domain credential as part of the pre-check. It is responsibility of Admin to make sure that all the input parameters in fabricConfig file is correct. anyway, if the credentials are obsolete, the deployment will fail at the time of authentication.

**Comment by JMesser81** [comment] 2017-01-20 23:32
I think we should fix this, yes?

**Comment by kallie-b** [comment] 2017-04-18 03:39
@manishmsft -- Any progress here? Is this still an active issue?

**Comment by sanjkum** [comment] 2017-07-12 08:25
The issue is resolved in latest service template. Now we are validating the domain credentials provided in configuration file before triggering the deployment and the deployment does not start if the provided credential is incorrect.

**Comment by sanjkum** [comment] 2017-07-12 08:26
@kallie-b  - 

The issue is resolved in latest service template. Now we are validating the domain credentials provided in configuration file before triggering the deployment and the deployment does not start if the provided credential is incorrect.

**Comment by nnamuhcs** [comment] 2017-11-09 05:18
Script will rely on the service template for the domain password validation in the latest VMM SDN Express script. Closed it now. Thanks.

**Closed by nnamuhcs** 2017-11-09 05:18 UTC
Labels: SDNExpress, VMMSDNExpress
